// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkgwqkpwmblhinbzaqub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZ3dxa3B3bWJsaGluYnphcXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzIxMzUsImV4cCI6MjA2OTEwODEzNX0.KmTBDi6aWOnYTt8mFt2hyA3R8z-mwxV8-DHtA0yh36U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});